# Generated by Django 5.1.3 on 2024-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
