# Generated by Django 5.1.3 on 2024-12-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='name',
            field=models.CharField(default='name was not enter', max_length=200),
        ),
    ]
